//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedDeposit
    {
        public int FixedDepositId { get; set; }
        public int Currency { get; set; }
        public double Rate { get; set; }
        public double FromSlab { get; set; }
        public double ToSlab { get; set; }
    }
}
