//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmarketingApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_contactus
    {
        public int Contact_id { get; set; }

        [Required(ErrorMessage ="Name is required")]
        public string Contact_Name { get; set; }

        [Required(ErrorMessage ="Email ID is required")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Invalid Email Address")]
        [EmailAddress(ErrorMessage ="Email Address is not Valid")]
        public string Email_Address { get; set; }
        public string Phone_No { get; set; }
        public string Account_holder { get; set; }
        public string Preferred_Branch { get; set; }
        public string Query_Type { get; set; }
        public string Message { get; set; }
    }
}
